version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule: { interval: "weekly", day: "wednesday" }
    open-pull-requests-limit: 5
    labels: ["area:deps", "automated"]
  - package-ecosystem: "pip"
    directory: "/"
    schedule: { interval: "weekly", day: "monday" }
    open-pull-requests-limit: 10
    labels: ["area:deps", "automated"]
    commit-message: { prefix: "deps", prefix-development: "deps-dev" }
  - package-ecosystem: "npm"
    directory: "/"
    schedule: { interval: "weekly", day: "tuesday" }
    open-pull-requests-limit: 10
    labels: ["area:deps", "automated"]
    commit-message: { prefix: "deps", prefix-development: "deps-dev" }
  - package-ecosystem: "cargo"
    directory: "/"
    schedule: { interval: "weekly", day: "thursday" }
    open-pull-requests-limit: 10
    labels: ["area:deps", "automated"]
    commit-message: { prefix: "deps" }
